### ISSUE TITLE
Visual Issue when running on Mobile

### ISSUE THREAD

**Issue by PaulNaylor** [keijiro/LwrpVfxTest#1]
Hi Keijiro,
I loved your twitter post on VFX for the LWRP, as we're building mobile games and LWRP has very exciting potential for us. I downloaded and tweaked this LwrpVfxTest and it works wonderfully in the editor but when I put it on my Google Pixel 2XL it has a strange rendering defect where each particle is tiled many times. 
Here's the in-editor one.. (correct)
![InEditor](https://user-images.githubusercontent.com/777146/55454153-514dd980-5611-11e9-94e3-b48576a93ee2.png)

Here's the one from my phone... (incorrect)
![Screenshot_20190403-124726](https://user-images.githubusercontent.com/777146/55454289-f8327580-5611-11e9-8022-c9718432322c.png)

Is it something I'm doing wrong or not doing?
Cheers,
Paul.
LandShark Games.

**Comment by keijiro** [comment]
Could you submit a bug report about it from Unity Editor using Bug Reporter? The VFX dev team will take care of it.

It seems that there are some compatibility issues with Android devices. This kind of reports will help the team a lot.

**Comment by PaulNaylor** [comment]
Sure thing :) thanks
Edit: done.

**Comment by keijiro** [comment]
Thanks for taking time for it. Now I'm closing this issue because I think there is nothing to do in this repository. Please feel free to reopen for further questions.
